checkpoints_path: ./experiments/
evolutionary:
  generations: 5
  lambda: 3
  max_epochs: 10000
  mutation:
    add_connection: 0.0
    remove_connection: 0.0
    add_layer: 0.8
    reuse_layer: 0.8
    remove_layer: 0.8
    dsge_topological: 0.8
    dsge_non_topological: 0.8
    train_longer: 0.2
  fitness:
    metric_name: accuracy
network:
  architecture:
    reuse_layer: 0.8
    macro_structure:
      - learning
    output: softmax
    modules:
      - name: features
        network_structure_init: [1]
        network_structure: [1,2]
        levels_back: 1
      - name: classification
        network_structure_init: [1]
        network_structure: [1,2]
        levels_back: 1
  learning:
    data_splits:
      labelled:
        percentage: 100 # downstream_train + validation + evo_test = percentage
        downstream_train:
          partition_ratio: 0.8
          amount_to_use: 1.0
          replacement: false
        validation:
          partition_ratio: 0.0
          amount_to_use: 1.0
          replacement: false
        evo_test:
          partition_ratio: 0.2
          amount_to_use: 1.0
          replacement: false
    learning_type: supervised
    augmentation:
      train:
        random_crop:
          size: 32
          padding: 4
        random_horizontal_flip:
          probability: 0.5
      last_layer_train: null
      test: null
    default_train_time: 5
    fitness_metric: accuracy