# To be used to build a conda environment to run CEML on 
# macOS with MPS support. Tested on macOS 13.6.7 (01/07/2024)
name: evodenss

channels:
  - defaults

dependencies:
  - python=3.10
  - openblas=0.3.21  # https://stackoverflow.com/questions/70242015/python-how-to-solve-the-numpy-importerror-on-apple-silicon
  - pip=24.0
  - pytorch::pytorch=2.3.1
  - pytorch::torchvision=0.18.1
  - scikit-learn=1.4.2
  - pyyaml=6.0.1
  - dill=0.3.8
  - numpy=1.26.4 # https://github.com/pytorch/vision/issues/8536
  - pip:
    - pytest==8.2.2
    - parameterized==0.9.0
    - coverage==7.5.3
    - ruff==0.6.6
    - mypy==1.11.2
    - pydantic==2.8.2

  