name: evodenss
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip=24.0
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-cuda=12.1
  - jsonschema=4.22.0
  - scikit-learn=1.4.2
  - pyyaml=6.0.1
  - dill=0.3.8
  - numpy=1.26.4 # https://github.com/pytorch/vision/issues/8536
  - pip:
    - pytest==8.2.2
    - parameterized==0.9.0
    - coverage==7.5.3
    - ruff==0.6.6
    - mypy==1.11.2
    - pydantic==2.8.2
