########################################
###############   RUFF   ###############
########################################

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv"
]

# Same as Black.
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = ["F", "E", "W291", "W292"]
ignore = ["E741"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.lint.flake8-tidy-imports]
# Disallow all relative imports.
ban-relative-imports = "all"




########################################
###############   MYPY   ###############
########################################

[tool.mypy]
python_version = "3.10"
files = [
    "evodenss/",
    "tests/"
]
enable_incomplete_feature = ["Unpack"]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
follow_imports_for_stubs = false
ignore_missing_imports = true
strict= true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

########################################
#############   PYLANCE   ##############
########################################

[tool.pyright]
root = ['.']
include = ["evodenss", "tests"]
exclude = ["**/__pycache__"]

useLibraryCodeForTypes = true

typeCheckingMode = "basic"

reportMissingTypeStubs = "none"
reportUnknownMemberType = "none"