checkpoints_path: ../../results/experiment_bt_10

evolutionary:
  generations: 100
  lambda: 6
  max_epochs: 100000
  mutation:
    add_connection: 0.0
    remove_connection: 0.0
    add_layer: 0.3
    reuse_layer: 0.15
    remove_layer: 0.3
    dsge_topological: 0.15
    dsge_non_topological: 0.3
    train_longer: 0.03
  fitness:
    metric_name: downstream_accuracy
    parameters:
      downstream_mode: freeze
      downstream_epochs: 30
      batch_size: 2048
      optimiser_type: "adam"
      optimiser_parameters:
        lr: 0.001
        weight_decay: 0.000001
        beta1: 0.9
        beta2: 0.999

network:
  architecture:
    reuse_layer: 0.15
    output: identity
    projector:
      - 512
      - 128
    modules:
      - name: features
        network_structure_init:
          min_expansions: 4
          max_expansions: 7
        network_structure:
          min_expansions: 4
          max_expansions: 30
        levels_back: 1
    extra_components:
      - learning
      - pretext
  learning:
    data_splits:
      labelled:
        percentage: 10
        downstream_train:
          partition_ratio: 0.08
          amount_to_use: 1.0
          replacement: false
        validation:
          partition_ratio: 0.0
          amount_to_use: 1.0
          replacement: false
        evo_test:
          partition_ratio: 0.02
          amount_to_use: 1.0
          replacement: false
      unlabelled:
        # pretext_train + downstream_train <= percentage
        pretext_train:
          amount_to_use: 1.0
          replacement: false
    learning_type: self-supervised
    default_train_time: 120
    augmentation:
      pretext:
        input_a:
          random_resized_crop:
            size: 32
          random_horizontal_flip:
            probability: 0.5
          color_jitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
            probability: 0.8
          random_grayscale:
            probability: 0.2
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
        input_b:
          random_resized_crop:
            size: 32
          random_horizontal_flip:
            probability: 0.5
          color_jitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
            probability: 0.8
          random_grayscale:
            probability: 0.2
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
      downstream:
        random_resized_crop:
          size: 32
        random_horizontal_flip:
          probability: 0.5
        color_jitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
          probability: 0.8
        random_grayscale:
          probability: 0.2
        normalize:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
      test:
        normalize:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
