name: Lint code and run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with ruff
      run: |
        ruff check
    - name: Analysing the code with mypy
      run: |
        mypy --config-file=pyproject.toml $(git ls-files '*.py')
    - name: Run unit tests
      run: |
        coverage run --source evodenss -m pytest -v tests --cache-clear 